steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--build-arg=VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}'
      - '--build-arg=VITE_SUPABASE_ANON_KEY=${_VITE_SUPABASE_ANON_KEY}'
      - '-t'
      - 'gcr.io/jax-points-tracker/jax-points'
      - '.'

images:
  - 'gcr.io/jax-points-tracker/jax-points'

# Default substitutions (these will be overridden by command line)
substitutions:
  _VITE_SUPABASE_URL: 'placeholder'
  _VITE_SUPABASE_ANON_KEY: 'placeholder'
